name: Benchmark
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - "**/*.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bench:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: curioswitch/go-build/.github/actions/setup-go@338fc9f50df6cb664134b5c600630dcbc483d81f # v0.7.3

      - name: setup re2 for cgo
        run: sudo apt-get update && sudo apt-get install -y libre2-dev

      - run: go run ./build bench-all

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: results
          path: build/*bench*.txt
