name: Refresh Go Cache

on:
  push:
    branches:
      - main
    paths:
      - go.work
      - "**/go.mod"
      - "**/versions.go"
      - .github/workflows/refresh-go-cache.yaml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  refresh:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - ubuntu-24.04
          - windows-2025
    uses: curioswitch/go-build/.github/workflows/export-refresh-go-cache.yaml@7d855da299ce7a10188c909a58328fc21ed89c40 # v0.9.0
    with:
      runner: ${{ matrix.os }}
