name: Renovate Dependencies

on:
  schedule:
    # https://crontab.guru/#5_12_*_*_1
    - cron: "5 12 * * 1"
  workflow_dispatch:

jobs:
  renovate:
    uses: curioswitch/go-build/.github/workflows/export-renovate.yaml@dd0ed390a0f1326e9426d4adb1b6ec2a97320a45 # v0.8.2
    with:
      github_app_id: ${{ vars.WASILIBS_APP_ID }}
    secrets:
      github_app_key: ${{ secrets.WASILIBS_APP_PRIVATE_KEY }}
