name: Renovate Dependencies

on:
  schedule:
    # https://crontab.guru/#5_12_*_*_1
    - cron: "5 12 * * 1"
  workflow_dispatch:

jobs:
  renovate:
    uses: curioswitch/go-build/.github/workflows/export-renovate.yaml@a2e54f5c6b6cff10d3b5ac6fcba4de7a411c6736 # v0.8.1
    with:
      github_app_id: ${{ vars.WASILIBS_APP_ID }}
    secrets:
      github_app_key: ${{ secrets.WASILIBS_APP_PRIVATE_KEY }}
